function q_result = quaternion_multiply(q_left, q_right, method)
  if strcmp(method, 'left')
    q_result = [q_left(1) -q_left(2) -q_left(3) -q_left(4);...
                q_left(2) q_left(1) -q_left(4) q_left(3);...
                q_left(3) q_left(4) q_left(1) -q_left(2);...
                q_left(4) -q_left(3) q_left(2) q_left(1)]*q_right;
  else
    q_result = [q_right(1) -q_right(2) -q_right(3) -q_right(4);...
                 q_right(2) q_right(1) q_right(4) -q_right(3);...
                 q_right(3) -q_right(4) q_right(1) q_right(2);...
                 q_right(4) q_right(3) -q_right(2) q_right(1)]*q_left;
  end

end

